# Change baseurl before deploy
baseurl = "https://ixff.github.io/"  # 站点url
languageCode = "en-us"
paginate = 5
title = "ixff"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"  # 模板语言

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = ""  # Disqus评论系统